---
- name: Install virtualenv package
  apt:
    name: python-virtualenv
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_time }}"

- name: Install packages required to create virtualenv
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_time }}"
  with_items: "{{ venv_packages }}"

- name: Create virtualenv
  command: virtualenv --python={{ venv_python }} {{ venv }}
  args:
    creates: "{{ venv }}"

- name: Create venv owner
  user:
    name: "{{ venv_owner }}"
    createhome: false
  when: venv_owner is defined and venv_owner

- name: Create venv group
  group:
    name: "{{ venv_group }}"
  when: venv_group is defined and venv_group

- name: Set ownership of virtualenv directory
  file:
    path: "{{ venv }}"
    state: directory
    owner: "{{ venv_owner | default(omit) }}"
    group: "{{ venv_group | default(omit) }}"
    recurse: yes

- name: Install pip requirements
  pip:
    requirements: "{{ venv_requirements }}"
    virtualenv: "{{ venv }}"
  when: venv_requirements is defined and venv_requirements
